[package]
name = "webseal"
version = "0.1.0"
edition = "2024"

[lib]
# cdylib tells Cargo to produce a C‑compatible dynamic library
crate-type = ["cdylib"]

[dependencies]
sealbindings = { git = "https://github.com/seal-runtime/sealbindings" }
tao = "0.35.3"
wry = { version = "0.55.1", features = [ "transparent" ] }
crossbeam-channel = "0.5.15"
